### ISSUE TITLE
Websocket Support?

### ISSUE THREAD

**Issue by joemccann** [CliffS/coinex.com#1]
First off, this is great work.  You saved me a ton of time from writing my own client.

I'm curious if you're going to add websocket support?

I can take a crack at it but I am not useful with Coffeescript.

**Comment by CliffS** [comment]
Sorry.  I don't have time to look at this at the moment.  But you'd enjoy Coffeescript once you get used to it.  PRs welcome.  
Of course, you could always write a module in ES6 Javascript and link it in.
